#!/usr/bin/env node
/**
 * parse-cosing.mjs
 *
 * Converts the official CosIng CSV export into a TypeScript module
 * that can be imported directly by openBeautyFacts.ts.
 *
 * Usage:
 *   1. Download CosIng from:
 *      https://ec.europa.eu/growth/tools-databases/cosing/index.cfm?fuseaction=search.results&search_term=&search_function=&search_restriction=&search_status=&search_vegan=&search_origin=&search_type=&restrict_to_active=true&restrict_to_approved=true&ResultsPerPage=1000&Excel=true
 *      → Save as  scripts/cosing_ingredients.csv
 *
 *   2. Run from the skinscan directory:
 *      node scripts/parse-cosing.mjs
 *
 *   3. The output is written to:
 *      services/cosing-db.ts
 *
 * CosIng CSV columns (semicolon-separated):
 *   INCI NAME ; INN NAME ; Ph. Eur. Name ; CAS No ; EC No ; EINECS/ELINCS No ;
 *   FUNCTION ; RESTRICTION ; DESCRIPTION ; STATUS
 */

import { createReadStream, writeFileSync } from "fs";
import { createInterface } from "readline";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const INPUT = resolve(__dirname, "cosing_ingredients.csv");
const OUTPUT = resolve(__dirname, "../services/cosing-db.ts");

// ─── Safety level heuristics ─────────────────────────────────────────────────
function inferSafety(restriction = "", description = "") {
  const r = (restriction + " " + description).toLowerCase();
  if (
    r.includes("prohibited") ||
    r.includes("interdit") ||
    r.includes("banned") ||
    r.includes("shall not") ||
    r.includes("carcinogen")
  )
    return "avoid";
  if (
    r.includes("restricted") ||
    r.includes("limit") ||
    r.includes("allergeni") ||
    r.includes("sensitiz") ||
    r.includes("irritant") ||
    r.includes("annex iii") ||
    r.includes("annex iv")
  )
    return "caution";
  return "safe";
}

// ─── Map CosIng FUNCTION string to short French label ────────────────────────
function mapFunction(raw = "") {
  const f = raw.toLowerCase();
  if (f.includes("emollient")) return "Émollient";
  if (f.includes("humectant")) return "Humectant";
  if (f.includes("surfactant") || f.includes("cleansing")) return "Tensioactif";
  if (f.includes("emulsifying") || f.includes("emulsifier")) return "Émulsifiant";
  if (f.includes("preserv")) return "Conservateur";
  if (f.includes("antioxidant")) return "Antioxydant";
  if (f.includes("fragrance") || f.includes("perfum")) return "Parfum";
  if (f.includes("uv absorber") || f.includes("uv filter")) return "Filtre UV";
  if (f.includes("viscosity") || f.includes("thickening")) return "Gélifiant";
  if (f.includes("conditioning")) return "Conditionneur";
  if (f.includes("soothing") || f.includes("skin conditioning")) return "Apaisant";
  if (f.includes("exfoliant") || f.includes("keratolytic")) return "Exfoliant";
  if (f.includes("colorant") || f.includes("colouring")) return "Colorant";
  if (f.includes("solvent")) return "Solvant";
  if (f.includes("chelating")) return "Chélateur";
  if (f.includes("buffering") || f.includes("ph adjust")) return "Régulateur pH";
  return raw.split(",")[0].trim() || "Ingrédient cosmétique";
}

// ─── Main ─────────────────────────────────────────────────────────────────────
async function main() {
  const rl = createInterface({ input: createReadStream(INPUT), crlfDelay: Infinity });
  const entries = [];
  let headerSkipped = false;

  for await (const line of rl) {
    if (!headerSkipped) { headerSkipped = true; continue; }
    // CosIng uses semicolons; some fields may be quoted
    const cols = line.split(";").map((c) => c.trim().replace(/^"|"$/g, ""));
    const inci        = cols[0]?.trim();
    const functions   = cols[6]?.trim() || "";
    const restriction = cols[7]?.trim() || "";
    const description = cols[8]?.trim() || "";

    if (!inci || inci.length < 2) continue;

    const key = inci.toLowerCase();
    const safety = inferSafety(restriction, description);
    const fnLabel = mapFunction(functions);

    // Build concerns from restriction text
    const concerns = [];
    if (restriction && restriction.length > 3 && restriction.toLowerCase() !== "none") {
      // Truncate long restriction text to a readable sentence
      concerns.push(restriction.slice(0, 120));
    }

    entries.push({ key, inci, fnLabel, safety, description, concerns });
  }

  console.log(`Parsed ${entries.length} CosIng entries`);

  // Generate TypeScript
  const lines = [
    `// AUTO-GENERATED by scripts/parse-cosing.mjs — do not edit manually`,
    `// Source: CosIng (European Commission Cosmetic Ingredients database)`,
    `// Regenerate: node scripts/parse-cosing.mjs`,
    ``,
    `export interface CosingEntry {`,
    `  commonName: string;`,
    `  function: string;`,
    `  safetyLevel: "safe" | "caution" | "avoid";`,
    `  concerns: string[];`,
    `  description: string;`,
    `}`,
    ``,
    `export const COSING_DB: Record<string, CosingEntry> = {`,
  ];

  for (const e of entries) {
    const escaped = (s) => s.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\${/g, "\\${");
    lines.push(
      `  ${JSON.stringify(e.key)}: {` +
      ` commonName: ${JSON.stringify(e.inci)},` +
      ` function: ${JSON.stringify(e.fnLabel)},` +
      ` safetyLevel: "${e.safety}",` +
      ` concerns: ${JSON.stringify(e.concerns)},` +
      ` description: ${JSON.stringify(e.description.slice(0, 300))},` +
      ` },`
    );
  }

  lines.push(`};`);
  lines.push(``);

  writeFileSync(OUTPUT, lines.join("\n"), "utf8");
  console.log(`✅  Written to ${OUTPUT}`);
}

main().catch((e) => { console.error(e); process.exit(1); });
