// Curated CosIng-sourced ingredient data.
// For the full ~25 000-entry database, run:  node scripts/parse-cosing.mjs
// (after downloading cosing_ingredients.csv from the European Commission website)

export interface CosingEntry {
  commonName: string;
  function: string;
  safetyLevel: "safe" | "caution" | "avoid";
  isAllergen?: boolean;
  concerns: string[];
  benefits: string[];
  description: string;
}

export const COSING_DB: Record<string, CosingEntry> = {
  // ── Solvants / bases ──────────────────────────────────────────────────────
  aqua: {
    commonName: "Eau purifiée",
    function: "Solvant",
    safetyLevel: "safe",
    concerns: [],
    benefits: ["Hydratation", "Support de formule"],
    description: "Eau purifiée utilisée comme solvant principal dans les formulations cosmétiques. Elle constitue la base de la plupart des émulsions, gels et lotions.",
  },
  glycerin: {
    commonName: "Glycérine",
    function: "Humectant",
    safetyLevel: "safe",
    concerns: [],
    benefits: ["Hydratation intense", "Douceur", "Protection barrière"],
    description: "Polyol naturel (issu de végétaux ou de synthèse) reconnu pour sa puissante action humectante. Attire et retient l'eau dans les couches supérieures de la peau, améliorant durablement la souplesse cutanée.",
  },
  // ── Émollients / corps gras ───────────────────────────────────────────────
  dimethicone: {
    commonName: "Diméthicone (Silicone)",
    function: "Émollient",
    safetyLevel: "safe",
    concerns: [],
    benefits: ["Texture soyeuse", "Lissant", "Film protecteur"],
    description: "Silicone fluide qui forme un film imperméable à la surface de la peau sans obstruer les pores. Confère une texture veloutée caractéristique et protège la peau des agressions extérieures.",
  },
  "cetearyl alcohol": {
    commonName: "Alcool cétéarylique",
    function: "Émulsifiant / Émollient",
    safetyLevel: "safe",
    concerns: [],
    benefits: ["Adoucissant", "Stabilisant d'émulsion"],
    description: "Alcool gras d'origine végétale (mélange de cétanol et de stéarol). Malgré son nom, il n'assèche pas la peau — il l'adoucit et stabilise les émulsions huile-dans-eau.",
  },
  "cetyl alcohol": {
    commonName: "Alcool cétylique",
    function: "Émollient",
    safetyLevel: "safe",
    concerns: [],
    benefits: ["Adoucissant", "Consistance"],
    description: "Alcool gras saturé dérivé de l'huile de coco. Agent d'épaississement et émollient qui améliore la texture et la sensation des crèmes.",
  },
  petrolatum: {
    commonName: "Vaseline (Petrolatum)",
    function: "Occlusif",
    safetyLevel: "safe",
    concerns: [],
    benefits: ["Hydratation intense", "Cicatrisation", "Barrière protectrice"],
    description: "Dérivé pétrolier hautement purifié. L'un des occlusifs les plus efficaces : il forme un film imperméable qui empêche la perte d'eau trans-épidermique. Recommandé pour les peaux très sèches ou fragilisées.",
  },
  squalane: {
    commonName: "Squalane",
    function: "Émollient",
    safetyLevel: "safe",
    concerns: [],
    benefits: ["Hydratation", "Antioxydant", "Non-comédonique"],
    description: "Hydrocarbure saturé analogue au squalène naturellement présent dans le sébum humain. D'origine végétale (olive, canne à sucre), il est léger, non-gras et compatible avec tous types de peau, y compris acnéique.",
  },
  // ── Humectants & actifs ───────────────────────────────────────────────────
  panthenol: {
    commonName: "Panthénol (Pro-Vitamine B5)",
    function: "Humectant",
    safetyLevel: "safe",
    concerns: [],
    benefits: ["Hydratation profonde", "Cicatrisation", "Apaisement", "Douceur"],
    description: "Précurseur de la vitamine B5 (acide pantothénique) qui pénètre profondément dans la peau où il est converti en acide pantothénique. Stimule la prolifération cellulaire, accélère la cicatrisation et apporte une hydratation durable.",
  },
  allantoin: {
    commonName: "Allantoïne",
    function: "Apaisant / Kératolytique doux",
    safetyLevel: "safe",
    concerns: [],
    benefits: ["Cicatrisation", "Apaisement", "Lissant"],
    description: "Composé naturellement présent dans la consoude et l'urine fœtale. Accélère le renouvellement cellulaire, favorise la cicatrisation et apaise les irritations. Idéal pour les peaux sensibles et irritées.",
  },
  urea: {
    commonName: "Urée",
    function: "Kératolytique / Humectant",
    safetyLevel: "safe",
    concerns: [],
    benefits: ["Exfoliation douce", "Hydratation profonde", "Ramollissement"],
    description: "Composant naturel du facteur naturel d'hydratation (NMF) de la peau. À faible concentration (≤5%), humectant puissant ; à haute concentration (≥10%), kératolytique qui élimine les cellules mortes. Efficace pour les peaux sèches et kératosiques.",
  },
  "hyaluronic acid": {
    commonName: "Acide hyaluronique",
    function: "Humectant / Repulpant",
    safetyLevel: "safe",
    concerns: [],
    benefits: ["Hydratation intense", "Repulpant", "Lissant rides"],
    description: "Polysaccharide naturellement présent dans le derme. Capable de retenir jusqu'à 1000× son poids en eau. Les formules modernes combinent plusieurs poids moléculaires : haut PM agit en surface, bas PM pénètre dans le derme pour une hydratation profonde.",
  },
  "sodium hyaluronate": {
    commonName: "Hyaluronate de sodium (AH)",
    function: "Humectant",
    safetyLevel: "safe",
    concerns: [],
    benefits: ["Hydratation", "Repulpant", "Cicatrisant"],
    description: "Sel sodique de l'acide hyaluronique, plus stable et soluble que la forme acide. Forme un film hydratant à la surface de la peau tout en pénétrant dans les couches superficielles de l'épiderme.",
  },
  betaine: {
    commonName: "Bétaïne",
    function: "Humectant",
    safetyLevel: "safe",
    concerns: [],
    benefits: ["Hydratation", "Douceur", "Anti-irritant"],
    description: "Acide aminé dérivé de la betterave à sucre. Excellent humectant qui améliore la tolérance cutanée des formules. Réduit l'irritation potentielle d'autres ingrédients comme les tensioactifs.",
  },
  // ── AHA / BHA / Exfoliants ────────────────────────────────────────────────
  "glycolic acid": {
    commonName: "Acide glycolique (AHA)",
    function: "Exfoliant chimique",
    safetyLevel: "caution",
    concerns: ["Photosensibilisant — appliquer SPF le matin", "Peut irriter les peaux sensibles", "Limité à 10% en leave-on selon le CSSC"],
    benefits: ["Exfoliation profonde", "Uniformisation du teint", "Anti-rides"],
    description: "Alpha-hydroxy acide (AHA) à la plus petite molécule, issu de la canne à sucre. Pénètre rapidement pour dissoudre les liaisons entre cellules mortes. Très efficace sur les irrégularités de teint, rides fines et pores. Nécessite une protection solaire obligatoire le matin.",
  },
  "lactic acid": {
    commonName: "Acide lactique (AHA)",
    function: "Exfoliant chimique",
    safetyLevel: "caution",
    concerns: ["Photosensibilisant — appliquer SPF le matin", "Déconseillé sur peau très réactive"],
    benefits: ["Exfoliation douce", "Hydratant (humectant à faible dose)", "Éclat"],
    description: "AHA d'origine naturelle (fermentation lactique). Plus doux que l'acide glycolique grâce à sa plus grande molécule. À la fois exfoliant et humectant — stimule le NMF. Recommandé pour débuter l'exfoliation chimique.",
  },
  "salicylic acid": {
    commonName: "Acide salicylique (BHA)",
    function: "Exfoliant chimique / Kératolytique",
    safetyLevel: "caution",
    concerns: ["Photosensibilisant modéré", "Déconseillé chez la femme enceinte", "Limité à 2% selon la réglementation EU"],
    benefits: ["Anti-acné", "Désincrustant pores", "Anti-pelliculaire"],
    description: "Beta-hydroxy acide liposoluble qui pénètre dans les pores pour les désincruster. Propriétés anti-inflammatoires et antimicrobiennes, idéal pour les peaux à tendance acnéique. Régule la kératinisation.",
  },
  "azelaic acid": {
    commonName: "Acide azélaïque",
    function: "Kératolytique / Anti-inflammatoire",
    safetyLevel: "safe",
    concerns: [],
    benefits: ["Anti-acné", "Dépigmentant", "Anti-rougeurs", "Anti-inflammatoire"],
    description: "Acide dicarboxylique naturellement présent dans les céréales. Inhibe la tyrosinase (dépigmentant), régule la kératinisation folliculaire (anti-acné) et possède des propriétés anti-inflammatoires. Actif polyvalent particulièrement adapté aux peaux rosacéiques.",
  },
  "alpha-arbutin": {
    commonName: "Alpha-Arbutine",
    function: "Dépigmentant",
    safetyLevel: "safe",
    concerns: [],
    benefits: ["Uniformisation du teint", "Anti-taches", "Éclat"],
    description: "Glycoside de l'hydroquinone d'origine naturelle (canneberge, raisin). Inhibe la tyrosinase sans les risques de l'hydroquinone. Agit progressivement sur les taches pigmentaires existantes et prévient leur formation.",
  },
  retinol: {
    commonName: "Rétinol (Vitamine A)",
    function: "Anti-âge / Renouvellement cellulaire",
    safetyLevel: "caution",
    concerns: ["Photosensibilisant — réserver à la routine du soir", "Déconseillé pendant la grossesse", "Peut provoquer rougeurs, desquamation au début"],
    benefits: ["Anti-rides", "Renouvellement cellulaire", "Anti-acné", "Uniformisation"],
    description: "Forme active de la vitamine A, référence en anti-âge. Stimule la production de collagène, accélère le renouvellement cellulaire et normalise la kératinisation. Nécessite une introduction progressive (1-2×/semaine) et une protection solaire stricte.",
  },
  niacinamide: {
    commonName: "Niacinamide (Vitamine B3)",
    function: "Actif multifonction",
    safetyLevel: "safe",
    concerns: [],
    benefits: ["Pores affinés", "Régulation sébum", "Anti-taches", "Renforcement barrière", "Anti-rides"],
    description: "Forme amide de la vitamine B3 (niacine). Actif aux bénéfices multiples cliniquement prouvés : réduit la visibilité des pores, régule la production de sébum, atténue les taches pigmentaires, renforce la barrière cutanée et lisse les rides fines. Compatible avec la plupart des actifs.",
  },
  "ascorbic acid": {
    commonName: "Acide ascorbique (Vitamine C pure)",
    function: "Antioxydant / Dépigmentant",
    safetyLevel: "caution",
    concerns: ["Instable à la lumière et à l'air (s'oxyde)", "pH bas nécessaire (<3.5) — peut irriter"],
    benefits: ["Antioxydant puissant", "Éclat", "Anti-taches", "Stimulation collagène"],
    description: "Forme pure de la vitamine C, la plus puissante mais aussi la moins stable. Inhibe la tyrosinase, stimule la synthèse de collagène et neutralise les radicaux libres. Conserver à l'abri de la lumière. Les formules à pH bas peuvent irriter les peaux sensibles.",
  },
  caffeine: {
    commonName: "Caféine",
    function: "Vasoconstricteur / Antioxydant",
    safetyLevel: "safe",
    concerns: [],
    benefits: ["Anti-poches", "Anti-cernes", "Antioxydant", "Drainant"],
    description: "Alcaloïde issu du café, du thé ou du guarana. Vasoconstricteur local qui réduit les poches et cernes en améliorant la microcirculation. Propriétés antioxydantes et capacité à inhiber les phosphodiestérases.",
  },
  // ── Filtres UV ────────────────────────────────────────────────────────────
  "titanium dioxide": {
    commonName: "Dioxyde de titane CI 77891",
    function: "Filtre UV minéral (UVB/UVA)",
    safetyLevel: "safe",
    concerns: [],
    benefits: ["Filtre UV large spectre", "Bien toléré", "Opacifiant"],
    description: "Filtre solaire minéral (physique) qui réfléchit et diffuse les rayons UV par action physique, sans réaction chimique avec la peau. Large spectre UVB/UVA. Recommandé pour les peaux sensibles et les enfants. Peut laisser un dépôt blanc sur les peaux foncées.",
  },
  "zinc oxide": {
    commonName: "Oxyde de zinc CI 77947",
    function: "Filtre UV minéral (UVA/UVB)",
    safetyLevel: "safe",
    concerns: [],
    benefits: ["Filtre UV large spectre", "Apaisant", "Anti-inflammatoire", "Zinc astringent"],
    description: "Filtre solaire minéral offrant une meilleure couverture UVA que le TiO₂. Propriétés anti-inflammatoires et apaisantes supplémentaires. Utilisé également comme actif anti-acné et dans les formules pour bébé.",
  },
  // ── Conservateurs ────────────────────────────────────────────────────────
  phenoxyethanol: {
    commonName: "Phénoxyéthanol",
    function: "Conservateur",
    safetyLevel: "caution",
    concerns: ["Limité à 1% en EU", "Déconseillé sur les fesses des nourrissons (ANSM)", "Peut irriter sur peaux très sensibles"],
    benefits: ["Large spectre antimicrobien", "Stable", "Compatible plupart des formules"],
    description: "Éther glycolique à action antimicrobienne large spectre. Conservateur le plus utilisé en cosmétique depuis le retrait des parabènes. Généralement bien toléré à 1% mais l'ANSM déconseille son usage sur les fesses des nourrissons.",
  },
  "methylparaben": {
    commonName: "Méthylparabène",
    function: "Conservateur",
    safetyLevel: "caution",
    concerns: ["Activité oestrogénique faible (perturbateur endocrinien potentiel)", "Controversé malgré son statut légal EU"],
    benefits: ["Très efficace à faible concentration", "Longue histoire d'usage sûr"],
    description: "Ester méthylique de l'acide para-hydroxybenzoïque. Conservateur autorisé en EU jusqu'à 0,4% (seul) ou 0,8% (combinaison). Fait l'objet d'une controverse scientifique sur son activité oestrogénique à très faible dose.",
  },
  ethylhexylglycerin: {
    commonName: "Éthylhexylglycérine",
    function: "Conservateur / Humectant",
    safetyLevel: "safe",
    concerns: [],
    benefits: ["Actif antimicrobien", "Sensation peau douce", "Souvent associé au phénoxyéthanol"],
    description: "Dérivé glycérolé à double action : conservateur antimicrobien et humectant. Utilisé seul ou en association avec le phénoxyéthanol pour réduire la concentration totale de ce dernier.",
  },
  "sodium benzoate": {
    commonName: "Benzoate de sodium",
    function: "Conservateur",
    safetyLevel: "caution",
    concerns: ["Peut former du benzène en présence d'acide ascorbique (Vitamine C) et d'UV"],
    benefits: ["Conservateur efficace pH acide"],
    description: "Sel sodique de l'acide benzoïque. Efficace en milieu acide (pH <5.5). Attention : en présence de vitamine C et d'exposition UV, peut former des traces de benzène — à éviter dans les formules combinant les deux.",
  },
  // ── Tensioactifs ────────────────────────────────────────────────────────
  "sodium laureth sulfate": {
    commonName: "SLS (Sodium Laureth Sulfate)",
    function: "Tensioactif nettoyant",
    safetyLevel: "caution",
    concerns: ["Peut perturber la barrière cutanée", "Irritant sur peaux sèches ou atopiques", "Élimine le sébum protecteur"],
    benefits: ["Nettoyant puissant", "Moussant abondant"],
    description: "Tensioactif anionique sulfaté très moussant, dérivé de l'huile de coco et d'oxyde d'éthylène. Efficace nettoyant mais considéré agressif pour les peaux sèches ou sensibles car il élimine les lipides protecteurs de la barrière cutanée.",
  },
  "coco glucoside": {
    commonName: "Coco glucoside",
    function: "Tensioactif doux",
    safetyLevel: "safe",
    concerns: [],
    benefits: ["Nettoyant très doux", "Biodégradable", "Adapté peaux sensibles"],
    description: "Tensioactif non-ionique d'origine 100% végétale (huile de coco + glucose). Nettoyant doux respectueux de la barrière cutanée. Compatible avec les peaux sensibles et les formules pour bébé.",
  },
  "cocamidopropyl betaine": {
    commonName: "Cocoamidopropyl bétaïne (CAPB)",
    function: "Tensioactif amphotère",
    safetyLevel: "caution",
    concerns: ["Peut provoquer des allergies de contact chez certains individus"],
    benefits: ["Adoucissant", "Anti-statique", "Améliore la mousse"],
    description: "Tensioactif amphotère dérivé de l'huile de coco. Doux, il adoucit l'effet des tensioactifs primaires et améliore la texture. Des cas rares d'allergie de contact ont été rapportés, souvent liés à des impuretés de fabrication (amidoamine).",
  },
  // ── Parfums / Allergènes EU ───────────────────────────────────────────────
  parfum: {
    commonName: "Parfum / Fragrance",
    function: "Parfum",
    safetyLevel: "caution",
    concerns: ["Peut contenir des allergènes EU non déclarés individuellement", "Première cause d'allergie cosmétique"],
    benefits: [],
    description: "Terme générique désignant un mélange de substances aromatiques. Réglementé par l'annexe III du règlement EU 1223/2009. La mention 'parfum' peut regrouper des dizaines de molécules dont certains allergènes de contact. Les personnes allergiques doivent préférer les formules 'fragrance-free'.",
  },
  limonene: {
    commonName: "Limonène",
    function: "Parfum",
    safetyLevel: "caution",
    concerns: ["Allergène EU — déclaration obligatoire >0,001% leave-on", "Peut irriter les peaux sensibles"],
    benefits: ["Note parfumée agrumes"],
    description: "Monoterpène présent naturellement dans les zestes d'agrumes et de nombreuses huiles essentielles. L'un des 26 allergènes EU à déclaration obligatoire. Sa forme oxydée (limonène oxydé) est plus allergisante — c'est pourquoi une bonne formulation évite son exposition à l'air.",
  },
  linalool: {
    commonName: "Linalool",
    function: "Parfum",
    safetyLevel: "caution",
    concerns: ["Allergène EU — déclaration obligatoire >0,001% leave-on", "L'oxydation augmente le potentiel allergisant"],
    benefits: ["Note florale / lavande"],
    description: "Alcool terpénique naturellement présent dans la lavande, la bergamote et de nombreuses fleurs. Allergène EU à déclaration obligatoire. La forme oxydée du linalool (lors d'exposition à l'air) est significativement plus allergisante.",
  },
  geraniol: {
    commonName: "Géraniol",
    function: "Parfum",
    safetyLevel: "caution",
    concerns: ["Allergène EU — déclaration obligatoire", "Fort potentiel sensibilisant"],
    benefits: ["Note florale / rose"],
    description: "Alcool terpénique naturellement présent dans le géranium, la rose et de nombreuses huiles essentielles. Allergène EU réglementé. Potentiel de sensibilisation relativement élevé parmi les monoterpènes.",
  },
  eugenol: {
    commonName: "Eugénol",
    function: "Parfum",
    safetyLevel: "caution",
    concerns: ["Allergène EU fort — déclaration obligatoire", "Déconseillé peaux sensibles ou atopiques"],
    benefits: ["Note épicée / clou de girofle"],
    description: "Phénol naturellement présent dans l'huile de clou de girofle et la cannelle. Allergène EU parmi les plus sensibilisants. Les personnes avec antécédents d'allergie au parfum doivent particulièrement l'éviter.",
  },
  // ── Régulateurs pH / Chélateurs ──────────────────────────────────────────
  "citric acid": {
    commonName: "Acide citrique",
    function: "Régulateur de pH / Chélateur",
    safetyLevel: "safe",
    concerns: [],
    benefits: ["Régule le pH", "Stabilise la formule"],
    description: "Acide organique présent dans les agrumes, utilisé comme régulateur de pH et chélateur. À faible concentration, ajuste le pH de la formule pour optimiser l'efficacité des actifs et la stabilité.",
  },
  "disodium edta": {
    commonName: "EDTA disodique",
    function: "Chélateur",
    safetyLevel: "safe",
    concerns: [],
    benefits: ["Stabilise la formule", "Améliore l'efficacité des conservateurs"],
    description: "Chélateur synthétique qui séquestre les ions métalliques (calcium, magnésium) dans l'eau et la formule. Améliore la stabilité des conservateurs et prévient le rancissement. Bien toléré à l'usage topique.",
  },
  // ── Céramides & renforcement barrière ────────────────────────────────────
  "ceramide np": {
    commonName: "Céramide NP",
    function: "Restructurant barrière cutanée",
    safetyLevel: "safe",
    concerns: [],
    benefits: ["Renforce la barrière lipidique", "Rétention d'eau", "Anti-irritant"],
    description: "Céramide de type non-hydroxy phytosphingosine, l'un des lipides naturellement présents dans la barrière cutanée (environ 50% des lipides lamellaires). Répare et renforce la barrière cutanée, prévient la perte d'eau et soulage les irritations.",
  },
  "ceramide ap": {
    commonName: "Céramide AP",
    function: "Restructurant barrière cutanée",
    safetyLevel: "safe",
    concerns: [],
    benefits: ["Renforce la barrière lipidique", "Cohésion inter-cellulaire"],
    description: "Céramide de type alpha-hydroxy acide phytosphingosine. Composant lipidique essentiel de l'épiderme qui maintient la cohésion des cornéocytes et l'intégrité de la barrière cutanée.",
  },
  // ── Gélifiants / Épaississants ────────────────────────────────────────────
  carbomer: {
    commonName: "Carbomère",
    function: "Gélifiant / Stabilisant",
    safetyLevel: "safe",
    concerns: [],
    benefits: ["Texture gel", "Stabilisant d'émulsion"],
    description: "Polymère d'acide acrylique hautement réticulé. À pH basique, il gonfle et forme un gel transparent. Très utilisé pour texturer les sérums, gels et émulsions légères. Neutre sur la peau.",
  },
  "xanthan gum": {
    commonName: "Gomme xanthane",
    function: "Gélifiant",
    safetyLevel: "safe",
    concerns: [],
    benefits: ["Texture", "Biodégradable", "Origine naturelle"],
    description: "Polysaccharide fermenté produit par la bactérie Xanthomonas campestris. Épaississant et gélifiant d'origine naturelle, biodégradable. Améliore la texture et la stabilité des formules.",
  },
  // ── Silicones spécifiques ────────────────────────────────────────────────
  cyclopentasiloxane: {
    commonName: "Cyclopentasiloxane (D5)",
    function: "Solvant volatile",
    safetyLevel: "caution",
    concerns: ["Perturbateur endocrinien potentiel (évaluation en cours)", "Interdit dans les produits rincés >0,1% au Canada"],
    benefits: ["Sèche rapidement", "Texture légère non-grasse"],
    description: "Silicone cyclique volatile (D5) qui s'évapore rapidement après application. Confère une texture légère et sèche instantanément. Fait l'objet d'une surveillance réglementaire croissante pour ses effets environnementaux et un potentiel perturbateur endocrinien faible.",
  },
  // ── Actifs botaniques ─────────────────────────────────────────────────────
  "aloe barbadensis": {
    commonName: "Aloe vera (gel)",
    function: "Apaisant / Hydratant",
    safetyLevel: "safe",
    concerns: [],
    benefits: ["Apaisant", "Hydratant", "Rafraîchissant", "Cicatrisant léger"],
    description: "Gel extrait des feuilles d'Aloe barbadensis Miller. Riche en mucopolysaccharides, vitamines (B, C, E) et acides aminés. Apaise les irritations, hydrate et favorise la régénération cutanée. Référence en soin post-solaire.",
  },
  "centella asiatica": {
    commonName: "Centella asiatica (CICA)",
    function: "Cicatrisant / Apaisant",
    safetyLevel: "safe",
    concerns: [],
    benefits: ["Cicatrisation", "Apaisement", "Renforcement barrière", "Anti-inflammatoire"],
    description: "Plante médicinale asiatique dont les extraits (madécassoside, asiaticoside) stimulent la synthèse de collagène et accélèrent la cicatrisation. L'un des actifs les plus populaires en k-beauty pour les peaux sensibles et irritées.",
  },
  bakuchiol: {
    commonName: "Bakuchiol",
    function: "Alternative au rétinol",
    safetyLevel: "safe",
    concerns: [],
    benefits: ["Anti-âge", "Fermeté", "Renouvellement cellulaire", "Sans photosensibilisation"],
    description: "Méroterpène végétal issu de la plante Psoralea corylifolia. Mécanisme d'action similaire au rétinol (activation des récepteurs rétinoïdes) sans ses effets secondaires (irritation, photosensibilisation). Utilisable le matin, pendant la grossesse. Études cliniques prometteuses.",
  },
};
